# Generated by Django 5.2.15 on 2026-08-22 19:47

from django.db import migrations


RELATION_COUNT_KEYS = '{"blocked_by_count": true, "blocking_count": true}'

FLAT_PROPERTIES_MODELS = [
    "ProjectUserProperty",
    "CycleUserProperties",
    "ModuleUserProperties",
    "IssueView",
]

NESTED_PROPERTIES_MODELS = [
    "WorkspaceUserProperties",
]


def backfill_relation_count_display_properties(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for model_name in FLAT_PROPERTIES_MODELS:
            table = apps.get_model("db", model_name)._meta.db_table
            cursor.execute(
                f"""
                UPDATE {table}
                SET display_properties = display_properties || '{RELATION_COUNT_KEYS}'::jsonb
                WHERE jsonb_typeof(display_properties) = 'object'
                  AND (NOT (display_properties ? 'blocked_by_count')
                       OR NOT (display_properties ? 'blocking_count'));
                """
            )
        for model_name in NESTED_PROPERTIES_MODELS:
            table = apps.get_model("db", model_name)._meta.db_table
            cursor.execute(
                f"""
                UPDATE {table}
                SET display_properties = jsonb_set(
                    display_properties,
                    '{{display_properties}}',
                    display_properties -> 'display_properties' || '{RELATION_COUNT_KEYS}'::jsonb,
                    true
                )
                WHERE jsonb_typeof(display_properties) = 'object'
                  AND jsonb_typeof(display_properties -> 'display_properties') = 'object'
                  AND (NOT (display_properties -> 'display_properties' ? 'blocked_by_count')
                       OR NOT (display_properties -> 'display_properties' ? 'blocking_count'));
                """
            )


def remove_relation_count_display_properties(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for model_name in FLAT_PROPERTIES_MODELS:
            table = apps.get_model("db", model_name)._meta.db_table
            cursor.execute(
                f"""
                UPDATE {table}
                SET display_properties = display_properties - 'blocked_by_count' - 'blocking_count'
                WHERE jsonb_typeof(display_properties) = 'object';
                """
            )
        for model_name in NESTED_PROPERTIES_MODELS:
            table = apps.get_model("db", model_name)._meta.db_table
            cursor.execute(
                f"""
                UPDATE {table}
                SET display_properties = jsonb_set(
                    display_properties,
                    '{{display_properties}}',
                    (display_properties -> 'display_properties') - 'blocked_by_count' - 'blocking_count',
                    true
                )
                WHERE jsonb_typeof(display_properties) = 'object'
                  AND jsonb_typeof(display_properties -> 'display_properties') = 'object';
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_relation_count_display_properties,
            reverse_code=remove_relation_count_display_properties,
        ),
    ]
